eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.app: DEBUG
resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    configs:
      default:
        register-health-indicator: true # <-- Configures it as a standard global indicator
    instances:
      ratingHotelBreaker:
        base-config: default # <-- Inherit global indicator behavior
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

  retry:
    retryAspectOrder: 2
    instances:
      ratingHotelRT:
        max-attempts: 3
        wait-duration: 5s

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: *

